[main]
file_path = "../private/tu2.xex"
#patch_file_path = "../private/default.xexp"
#patched_file_path = "../private/default_patched.xex"
out_directory_path = "../ppc"
switch_table_file_path = "LCE_TU2_switch_tables.toml"

skip_lr = false
skip_msr = false
ctr_as_local = false
xer_as_local = false
reserved_as_local = false
cr_as_local = false
non_argument_as_local = false
non_volatile_as_local = false


restgprlr_14_address = 0x82696f50
savegprlr_14_address = 0x82696f00
restfpr_14_address = 0x82697e8c
savefpr_14_address = 0x82697e40
restvmx_14_address = 0x8269a708
savevmx_14_address = 0x8269a470
restvmx_64_address = 0x8269a79c
savevmx_64_address = 0x8269a504



functions = [
	{ address = 0x821D1670, size = 0x8DC },
	{ address = 0x821D1678, size = 0x8D4 },
	{ address = 0x821DB828, size = 0x1F4C },
	{ address = 0x821DB830, size = 0x1F44 },
	{ address = 0x821DBDF4, size = 0x1F44 },
	{ address = 0x821dcaa4, size = 0x1F44 },
	{ address = 0x821dc9b8, size = 0x1F44 },
	{ address = 0x82224100, size = 0x3F4 },
	{ address = 0x822240f8, size = 0x400 },
	{ address = 0x822241f8, size = 0x3FC },
	{ address = 0x82284450, size = 0x22C0 },
	{ address = 0x82674708, size = 0xB7C },
	{ address = 0x82674B50, size = 0x734 },
	{ address = 0x82284448, size = 0x22C0 },
	{ address = 0x822994a8, size = 0xD6C },
	{ address = 0x822994a0, size = 0xD74 },
	{ address = 0x8229b2e0, size = 0x7A8 },
	{ address = 0x8229b2d8, size = 0x7B0 },
	{ address = 0x8229b724, size = 0x7B0 },
	{ address = 0x8229b4c0, size = 0x7B0 },
	{ address = 0x8231d2e0, size = 0x94C },
	{ address = 0x8231dc28, size = 0x54C },
	{ address = 0x8231E038, size = 0x54C },
	{ address = 0x8231DE84, size = 0x54C },
	{ address = 0x8231DC2C, size = 0x54C },
	{ address = 0x82330828, size = 0x224 },
	{ address = 0x823dacb8, size = 0x188 },
	{ address = 0x824c2920, size = 0x3C4 },
	{ address = 0x8258b348, size = 0x114 },
	{ address = 0x8258bed0, size = 0x360 },
	{ address = 0x8258bec8, size = 0x368 },
	{ address = 0x8258fe90, size = 0x554 },
	{ address = 0x8258fe88, size = 0x55C },
	{ address = 0x825901e8, size = 0x55C },
	{ address = 0x826747a8, size = 0x94 },
	{ address = 0x82674878, size = 0xB4 },
	{ address = 0x826749c0, size = 0x8C },
	{ address = 0x82674AD0, size = 0x8C },
	{ address = 0x82674a50, size = 0xFC },
	{ address = 0x82674b50, size = 0x8C },
	{ address = 0x82674c08, size = 0x17C },
	{ address = 0x82674d88, size = 0xA4 },
	{ address = 0x82674e68, size = 0x41C },
	{ address = 0x826e0a08, size = 0x224 },
	{ address = 0x826e33d0, size = 0x6A4 },
	{ address = 0x82736708, size = 0x1CC },
	{ address = 0x827805c8, size = 0x114 },
	{ address = 0x828014d0, size = 0x8C },
	{ address = 0x828078f0, size = 0xBC },
	{ address = 0x828079b0, size = 0xA4 },
	{ address = 0x82908130, size = 0xBC },
	{ address = 0x829081f0, size = 0xB8 },
	{ address = 0x829082a8, size = 0x80 },
	{ address = 0x82908328, size = 0x7C },
	{ address = 0x829083d0, size = 0x68 },
	{ address = 0x82908438, size = 0x64 },
	{ address = 0x82908598, size = 0x180 },
	{ address = 0x82908718, size = 0x5C },
	{ address = 0x829087a8, size = 0x198 },
	{ address = 0x82908940, size = 0x16C },
	{ address = 0x82908b18, size = 0x108 },
	{ address = 0x8290ad40, size = 0xE4 },
	{ address = 0x82931078, size = 0x190 },
	{ address = 0x82946778, size = 0x238 },
	{ address = 0x8294a008, size = 0x270 },
	{ address = 0x8294fca8, size = 0xB4 },
	{ address = 0x825fec18, size = 0x2a0 },
]

invalid_instructions = [
    { data = 0x00000000, size = 4 }, # Padding
]